### ISSUE TITLE
convert to solas-container style repo

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/crash-app-backend#4]
package up as container using solas-container as a template and set it up with gitlab. this is part of https://github.com/samsung-cnct/issues/issues/89. Please check off `crash-app-backend` on the original ticket when complete.

**Comment by oneilcin** [comment]
This does not fit the current solas repo gitlab file.  
This is a case for a custom golang application that needs to be compiled and tested, and then the image is pushed to quay.
Alika has a great example:
https://github.com/alika/cyklops-events/blob/c06b387c9125f9f35223ae35e81bc62df76106e1/.gitlab-ci.yml

**Comment by oneilcin** [comment]
Completed with these pull requests:

https://github.com/samsung-cnct/crash-app-backend/pull/5
https://github.com/samsung-cnct/crash-app-backend/pull/6
https://github.com/samsung-cnct/crash-app-backend/pull/7
